config/routes.rb
Rails.application.routes.draw do
  resources :workouts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/workout.rb
class Workout < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
    @data = Workout.group(:type_of_exercise).count
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
    @workout = Workout.find(params[:id])
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to workouts_url, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :index, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workout_params
      params.require(:workout).permit(:type_of_exercise, :minutes, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goodboy</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
  </head>
  

  <body>
  <nav>
    <div class="nav-wrapper">
      <img src="/GoodBoy_logo.png" id="logo" class="brand-logo center">
      
    </div>
  </nav>

    <%= yield %>

    
      
  </body>
</html>

app/views/workouts/_form.html.erb
<div class="form">

<%= form_with(model: workout, local: true) do |form| %>
  <% if workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
        <% workout.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type_of_exercise %>
    <%= form.text_field :type_of_exercise %>
  </div>

  <div class="field">
    <%= form.label :minutes %>
    <%= form.number_field :minutes %>
  </div>

  <div>
  <%= form.label :date %>
  <%= form.text_field :date %>
  </div>

  <div id:"submit-button" class="actions">
    <%= form.submit class: "waves-effect waves-light btn-large" %>
  </div>
<% end %>





</div>

app/views/workouts/edit.html.erb
<div class="form-header">
<h1>Editing Workout</h1>
</div>

<%= render 'form', workout: @workout %>

<div class="back-button">
<%= link_to 'Back', workouts_path, class: "waves-effect waves-light btn-small" %>
</div>

app/views/workouts/index.html.erb
<%= link_to 'Profile', workouts_path, data: {toggle: "modal", target: "#modal1"}, class: "waves-effect waves-light btn modal-trigger" %>
 

<!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
    <img id="profile-pic" class="circle responsive-img" src="/joe.jpg">
      <h3>Joey Tribbiani</h3>
      <h5>Age: 8 yrs</h5>
      <h5>Weight: 72 lbs</h5>
      <h5>Breed: I'm a lot of things</h5>
      <p> About me: I looooove my parents. Especially mom. We go on walks all the time! I also have a brother who I love but he beats me up sometimes. Sometimes I starve myself hoping my parents give me human food. It's worth the wait!!!
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
    </div>
  </div>
  

<div class="header">
<h2> <%= Date.today.strftime("%B %d, %Y") %> </h2>
</div>




<%= pie_chart @data, donut: true, colors: ["#fd7c6e", "#fd9b8f", "#fde2b4", "#49c5ce", "#006d99" ] %>


<p id="notice"><%= notice %></p>

<table class="highlight">
  <thead>
    <tr>
      <th scope="col">Type of Exercise</th>
      <th scope="col">Minutes</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
  <% @workouts.each do |workout| %>
    <tr>
    
      <td><%= workout.type_of_exercise %></td>
      <td><%= workout.minutes %></td>
      <td><%= workout.date %></td>
      <!-- <td><%= link_to 'See Workout', workout %></td> -->
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Delete', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      
    
  </tbody>
<% end %>
</table>




<br>

<div class="fixed-action-btn">
    <%= link_to '+', new_workout_path, class: "btn-floating btn-large waves-effect waves-light blue" %>
    </div>

   

    

app/views/workouts/new.html.erb
<div class="form-header">
<h3>New Workout</h3>
</div>

<%= render 'form', workout: @workout %>

<div class="back-button">
<%= link_to 'Back', workouts_path, class: "waves-effect waves-light btn-small" %>
</div>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type of exercise:</strong>
  <%= @workout.type_of_exercise %>
</p>

<p>
  <strong>Minutes:</strong>
  <%= @workout.minutes %>
</p>

<p>
  <strong>Date:</strong>
  <%= @workout.date %>
</p>

<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>